# Generated by Django 5.1.4 on 2025-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='register_data',
            field=models.DateField(auto_now=True),
        ),
    ]
